// SPDX-License-Identifier: Apache-2.0
//
// Install the runtime shim that .mcp.json's `command` field points at.
// Without this, `lodestone init` writes a .mcp.json referencing a binary
// that does not exist; the editor's MCP launcher then fails to start the
// server. The shim is a tiny shell wrapper that invokes the bundled
// `@lodestone/mcp-server/dist/server.js` via the host Node.
//
// Why a shim instead of pointing .mcp.json directly at server.js:
//   - The shim path is stable across npm install strategies (global,
//     local, pnpm, npx) and across machines that share the repo.
//   - .mcp.json can be checked into git: the path is repo-relative-shaped
//     (always under <repoRoot>/.lodestone/runtime/) without leaking
//     node_modules layout.
//   - Editors expect a single executable in `command`. The shim gives
//     us one regardless of how Node was installed.

import { chmodSync, existsSync, mkdirSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";

import { writeFileAtomic } from "./atomic.js";

/** The shim's path under .lodestone/. Mirrors `RUNTIME_ENTRY_REL` in
 * mcp-config.ts — keep these in sync. */
const RUNTIME_ENTRY_REL = path.join("runtime", "lodestone-mcp");

export interface RuntimeInstallResult {
  action: "created" | "updated";
  path: string;
  /** Absolute path of the @lodestone/mcp-server entry the shim wraps. */
  serverPath: string;
}

/**
 * Resolve the absolute path to `@lodestone/mcp-server/dist/server.js`.
 *
 * Uses createRequire from this module so resolution works whether the
 * cli was installed via npm/pnpm (sibling under node_modules) or run
 * out of a workspace checkout (sibling under packages/).
 */
function resolveMcpServerEntry(): string {
  const req = createRequire(import.meta.url);
  // `@lodestone/mcp-server` exports `./dist/index.js` as `.`. We need the
  // bin entry — `dist/server.js` — which lives next to dist/index.js.
  // Resolving the package main avoids needing `./package.json` in the
  // package's `exports` map.
  const mainEntry = req.resolve("@lodestone/mcp-server");
  const distDir = path.dirname(mainEntry);
  const serverPath = path.join(distDir, "server.js");
  if (!existsSync(serverPath)) {
    throw new Error(
      `@lodestone/mcp-server is installed but ${serverPath} does not exist. ` +
        `Re-run 'pnpm install && pnpm -r build' (workspace) or reinstall the package.`,
    );
  }
  return serverPath;
}

/**
 * Create or refresh the runtime shim at <repoRoot>/.lodestone/runtime/lodestone-mcp.
 *
 * Always (re)writes the shim so a stale absolute server path from a
 * prior install on another machine is corrected. Mode 0755.
 *
 * On Windows, a POSIX shell shim is non-functional. v0.1 ships a clear
 * fail rather than silently producing a broken install on win32.
 */
export function installRuntime(repoRoot: string): RuntimeInstallResult {
  if (process.platform === "win32") {
    throw new Error(
      "Lodestone v0.1 runtime shim is POSIX-only. Windows support is a tracked v0.2 item; " +
        "in the meantime, use WSL2.",
    );
  }
  const serverPath = resolveMcpServerEntry();
  const shimPath = path.join(repoRoot, ".lodestone", RUNTIME_ENTRY_REL);
  const existed = existsSync(shimPath);

  // Quote the server path so spaces / special chars don't break exec.
  // Use double-quotes; the path is server-resolved (we control it),
  // not friend-supplied.
  const body =
    `#!/bin/sh\n` +
    `# Lodestone runtime shim — generated by 'lodestone init'.\n` +
    `# Do not edit by hand; re-run 'lodestone init' to regenerate.\n` +
    `exec node "${serverPath}" "$@"\n`;

  mkdirSync(path.dirname(shimPath), { recursive: true });
  writeFileAtomic(shimPath, body);
  chmodSync(shimPath, 0o755);

  return {
    action: existed ? "updated" : "created",
    path: shimPath,
    serverPath,
  };
}
