// SPDX-License-Identifier: Apache-2.0
//
// Write `.lodestone/lodestone.toml` during `init`. The MCP server (§13)
// hard-fails on a missing toml at boot; the CLI loader falls through to
// schema defaults. v0.1.4 fix: produce the minimal toml so the MCP
// server boot path always succeeds after init.
//
// Idempotent — re-running `init` does NOT overwrite an existing toml
// (the operator may have edited it). Only writes if absent.

import { existsSync } from "node:fs";
import path from "node:path";

import { writeFileAtomic } from "./atomic.js";

export interface TomlInstallResult {
  action: "created" | "preserved";
  path: string;
}

/** Serialize a friend-safe minimal toml. Only sets `project.name` so all
 * other fields fall through to the canonical zod schema defaults. */
function defaultBody(projectName: string): string {
  // Basic TOML escape — names with quotes / backslashes get escaped.
  // We could pull in a toml stringifier, but the surface is one string.
  const escaped = projectName.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return (
    `# Lodestone project config — generated by 'lodestone init'.\n` +
    `# Edit values below to override schema defaults; see docs/CONFIG.md.\n` +
    `# Re-running 'init' will NOT overwrite this file.\n` +
    `\n` +
    `[project]\n` +
    `name = "${escaped}"\n`
  );
}

/** Write `<repoRoot>/.lodestone/lodestone.toml` if it doesn't exist. */
export function writeLodestoneToml(repoRoot: string): TomlInstallResult {
  const tomlPath = path.join(repoRoot, ".lodestone", "lodestone.toml");
  if (existsSync(tomlPath)) {
    return { action: "preserved", path: tomlPath };
  }
  const projectName = path.basename(repoRoot);
  writeFileAtomic(tomlPath, defaultBody(projectName));
  return { action: "created", path: tomlPath };
}
